version: '3.8'

services:
  tare:
    build:
      context: .
      dockerfile: Dockerfile
    image: tare:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ~/tare/db:/root/tare/db
      - ~/tare/logs:/root/tare/logs
      - ~/tare/upload/images:/root/tare/upload/images
    env_file:
      - ~/tare/.env.test
      #- /home/user/tare/.env.prod